### ISSUE TITLE
Lora-app-server  not running 

### ISSUE THREAD

**Issue by varunsavita** [brocaar/chirpstack-network-server#443] opened 2019-10-24 12:03 UTC
FATA[0000] error loading config file                     config=/etc/lora-app-server/lora-app-server.toml error="open /etc/lora-app-server/lora-app-server.toml: permission denied"

**Comment by varunsavita** [comment] 2019-10-24 12:04
FATA[0000] error loading config file                     config=/etc/lora-app-server/lora-app-server.toml error="open /etc/lora-app-server/lora-app-server.toml: permission denied"

**Comment by wolftrax5** [comment] 2019-10-24 17:53
I think the problem is not access to config, for permissions, try run it with sudo

**Comment by varunsavita** [comment] 2019-10-28 07:25
ubuntu@ip-172-31-25-243:~$ lora-app-server --config /etc/lora-app-server/lora-app-server.toml
FATA[0000] error loading config file                     config=/etc/lora-app-server/lora-app-server.toml error="open /etc/lora                       -app-server/lora-app-server.toml: permission denied"
ubuntu@ip-172-31-25-243:~$ sudo lora-app-server --config /etc/lora-app-server/lora-app-server.toml
INFO[0000] starting LoRa App Server                      docs="https://www.loraserver.io/" version=3.4.0-test.2
INFO[0000] storage: setting up storage package
INFO[0000] storage: setup metrics
INFO[0000] storage: setting up Redis pool
INFO[0000] storage: connecting to PostgreSQL database
INFO[0000] storage: applying PostgreSQL data migrations
FATA[0000] setup storage error: storage: applying PostgreSQL data migrations error: pq: type "hstore" does not exist handling 0                       041_device_variables.sql
ubuntu@ip-172-31-25-243:~$

**Comment by varunsavita** [comment] 2019-10-28 07:52
loraserver_as=> create extension hstore;
ERROR:  permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.

**Comment by varunsavita** [comment] 2019-10-28 08:01
i created "create extension hstore;"
now this error came.

ubuntu@ip-172-31-25-243:~$ sudo lora-app-server --config /etc/lora-app-server/lora-app-server.toml
INFO[0000] starting LoRa App Server                      docs="https://www.loraserver.io/" version=3.4.0-test.2
INFO[0000] storage: setting up storage package
INFO[0000] storage: setup metrics
INFO[0000] storage: setting up Redis pool
INFO[0000] storage: connecting to PostgreSQL database
INFO[0000] storage: applying PostgreSQL data migrations
INFO[0000] storage: PostgreSQL data migrations applied   count=0
INFO[0000] integration/mqtt: TLS config is empty
INFO[0000] integration/mqtt: connecting to mqtt broker   server="tcp://localhost:1883"
INFO[0000] api/as: starting application-server api       bind="0.0.0.0:8001" ca_cert= tls_cert= tls_key=
FATA[0000] setup api error: setup application-server api error: start application-server api listener error: listen tcp 0.0.0.0:8001: bind: address already in use
ubuntu@ip-172-31-25-243:~$

**Comment by brocaar** [comment] 2019-11-13 10:33
I'm closing this issue as this is related to configuration, not a bug or feature request. I think the error explains well what the issue is:

> start application-server api listener error: listen tcp 0.0.0.0:8001: bind: address already in use

**Closed by brocaar** 2019-11-13 10:33 UTC
